-- ============================================
-- SISTEM ANTREAN WAWANCARA BPS 2026
-- SUPABASE DATABASE SETUP
-- ============================================
-- Jalankan script ini di SQL Editor Supabase
-- Dashboard > SQL Editor > New Query
-- ============================================

-- CATATAN: Jalankan script ini SETELAH script supabase-setup.sql

-- ============================================
-- 1. TABEL PESERTA (Data peserta dari Sobat BPS)
-- ============================================
DROP TABLE IF EXISTS public.peserta CASCADE;

CREATE TABLE public.peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(16) NOT NULL UNIQUE,
    sobat_id VARCHAR(20) NOT NULL UNIQUE,
    nama TEXT NOT NULL,
    pasfoto_url TEXT,
    ktp_url TEXT,
    ijazah_url TEXT,
    alamat_lengkap TEXT,
    pendidikan_terakhir TEXT,
    pekerjaan TEXT,
    
    -- Data tambahan untuk wawancara
    posisi_dilamar TEXT DEFAULT 'Petugas Pencacah',
    tanggal_wawancara DATE,
    waktu_wawancara TIME,
    nomor_antrean VARCHAR(10),
    
    -- Status dan Hasil Wawancara
    status VARCHAR(20) DEFAULT 'Terdaftar', 
    -- Status: Terdaftar, Hadir, Menunggu, Diwawancara, Lulus, Tidak Lulus, Ditinjau, Tidak Hadir
    
    -- Penilaian
    nilai_total INTEGER DEFAULT 0,
    nilai_teknis INTEGER DEFAULT 0,       -- Skala 1-5
    nilai_komunikasi INTEGER DEFAULT 0,   -- Skala 1-5
    nilai_sikap INTEGER DEFAULT 0,        -- Skala 1-5
    catatan_pewawancara TEXT,
    
    -- Metadata
    pewawancara_id TEXT REFERENCES public.profiles(id),
    durasi_wawancara INTEGER DEFAULT 0,   -- dalam detik
    waktu_mulai_wawancara TIMESTAMP WITH TIME ZONE,
    waktu_selesai_wawancara TIMESTAMP WITH TIME ZONE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index untuk peserta
CREATE INDEX idx_peserta_nik ON public.peserta(nik);
CREATE INDEX idx_peserta_sobat_id ON public.peserta(sobat_id);
CREATE INDEX idx_peserta_status ON public.peserta(status);
CREATE INDEX idx_peserta_tanggal ON public.peserta(tanggal_wawancara);
CREATE INDEX idx_peserta_nomor_antrean ON public.peserta(nomor_antrean);

-- ============================================
-- 2. UPDATE TABEL JOBS UNTUK POSISI BPS
-- ============================================
DELETE FROM public.jobs WHERE true;

INSERT INTO public.jobs (title, is_active) VALUES 
('Petugas Pencacah', true),
('Pengawas', true),
('Koordinator Statistik Kecamatan', true);

-- ============================================
-- 3. ROW LEVEL SECURITY UNTUK PESERTA
-- ============================================
ALTER TABLE public.peserta ENABLE ROW LEVEL SECURITY;

-- Policy untuk melihat peserta (admin dan interviewer)
CREATE POLICY "Staff can view peserta" 
ON public.peserta FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role IN ('admin', 'interviewer')
  )
);

-- Policy untuk insert peserta (hanya admin)
CREATE POLICY "Admin can insert peserta" 
ON public.peserta FOR INSERT 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role = 'admin'
  )
);

-- Policy untuk update peserta (admin dan interviewer)
CREATE POLICY "Staff can update peserta" 
ON public.peserta FOR UPDATE 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role IN ('admin', 'interviewer')
  )
);

-- Policy untuk delete peserta (hanya admin)
CREATE POLICY "Admin can delete peserta" 
ON public.peserta FOR DELETE 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role = 'admin'
  )
);

-- ============================================
-- 4. FUNCTION UNTUK CHECK-IN PESERTA
-- ============================================
CREATE OR REPLACE FUNCTION checkin_peserta(p_nik VARCHAR(16))
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    peserta_record RECORD;
    new_nomor_antrean VARCHAR(10);
    current_count INTEGER;
BEGIN
    -- Cari peserta berdasarkan NIK
    SELECT * INTO peserta_record FROM public.peserta WHERE nik = p_nik;
    
    IF peserta_record IS NULL THEN
        RETURN jsonb_build_object(
            'status', 'error',
            'message', 'NIK tidak ditemukan dalam daftar peserta'
        );
    END IF;
    
    IF peserta_record.status NOT IN ('Terdaftar', 'Hadir') THEN
        RETURN jsonb_build_object(
            'status', 'error',
            'message', 'Peserta sudah melakukan check-in sebelumnya'
        );
    END IF;
    
    -- Generate nomor antrean
    SELECT COUNT(*) + 1 INTO current_count 
    FROM public.peserta 
    WHERE status IN ('Hadir', 'Menunggu', 'Diwawancara', 'Lulus', 'Tidak Lulus', 'Ditinjau')
    AND DATE(updated_at) = CURRENT_DATE;
    
    new_nomor_antrean := 'A-' || LPAD(current_count::TEXT, 3, '0');
    
    -- Update status dan nomor antrean
    UPDATE public.peserta
    SET status = 'Menunggu',
        nomor_antrean = new_nomor_antrean,
        updated_at = NOW()
    WHERE nik = p_nik;
    
    RETURN jsonb_build_object(
        'status', 'success',
        'message', 'Check-in berhasil',
        'nomor_antrean', new_nomor_antrean,
        'nama', peserta_record.nama
    );
END;
$$;

-- ============================================
-- 5. FUNCTION UNTUK MEMANGGIL PESERTA BERIKUTNYA
-- ============================================
CREATE OR REPLACE FUNCTION panggil_peserta_berikutnya(interviewer_id_input TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    matched_peserta RECORD;
BEGIN
    -- Set interviewer status ke busy
    UPDATE public.profiles 
    SET interviewer_status = 'busy' 
    WHERE id = interviewer_id_input;

    -- Cari peserta yang menunggu (FIFO berdasarkan nomor antrean)
    SELECT * INTO matched_peserta
    FROM public.peserta
    WHERE status = 'Menunggu'
    ORDER BY nomor_antrean ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED;

    IF matched_peserta.id IS NOT NULL THEN
        -- Update status peserta
        UPDATE public.peserta 
        SET status = 'Diwawancara',
            pewawancara_id = interviewer_id_input,
            waktu_mulai_wawancara = NOW(),
            updated_at = NOW()
        WHERE id = matched_peserta.id;

        -- Kembalikan data peserta
        RETURN jsonb_build_object(
            'status', 'success',
            'peserta_id', matched_peserta.id,
            'nama', matched_peserta.nama,
            'nik', matched_peserta.nik,
            'sobat_id', matched_peserta.sobat_id,
            'nomor_antrean', matched_peserta.nomor_antrean,
            'pasfoto_url', matched_peserta.pasfoto_url,
            'pendidikan_terakhir', matched_peserta.pendidikan_terakhir,
            'pekerjaan', matched_peserta.pekerjaan,
            'alamat_lengkap', matched_peserta.alamat_lengkap,
            'message', 'Peserta berhasil dipanggil'
        );
    ELSE
        -- Set interviewer kembali ke idle
        UPDATE public.profiles 
        SET interviewer_status = 'idle' 
        WHERE id = interviewer_id_input;
        
        RETURN jsonb_build_object(
            'status', 'empty', 
            'message', 'Tidak ada peserta dalam antrean'
        );
    END IF;
END;
$$;

-- ============================================
-- 6. FUNCTION UNTUK MENYELESAIKAN WAWANCARA
-- ============================================
CREATE OR REPLACE FUNCTION selesaikan_wawancara(
    p_peserta_id BIGINT,
    p_interviewer_id TEXT,
    p_nilai_teknis INTEGER,
    p_nilai_komunikasi INTEGER,
    p_nilai_sikap INTEGER,
    p_catatan TEXT,
    p_durasi INTEGER,
    p_hasil TEXT -- 'Lulus', 'Tidak Lulus', 'Ditinjau'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    total_nilai INTEGER;
BEGIN
    -- Hitung total nilai (rata-rata x 20 untuk skala 0-100)
    total_nilai := ROUND((p_nilai_teknis + p_nilai_komunikasi + p_nilai_sikap) * 100 / 15.0);

    -- Update data peserta
    UPDATE public.peserta
    SET 
        status = p_hasil,
        nilai_teknis = p_nilai_teknis,
        nilai_komunikasi = p_nilai_komunikasi,
        nilai_sikap = p_nilai_sikap,
        nilai_total = total_nilai,
        catatan_pewawancara = p_catatan,
        durasi_wawancara = p_durasi,
        waktu_selesai_wawancara = NOW(),
        updated_at = NOW()
    WHERE id = p_peserta_id AND pewawancara_id = p_interviewer_id;

    -- Set interviewer status ke idle
    UPDATE public.profiles 
    SET interviewer_status = 'idle' 
    WHERE id = p_interviewer_id;

    RETURN jsonb_build_object(
        'status', 'success',
        'message', 'Wawancara selesai, hasil tersimpan',
        'nilai_total', total_nilai,
        'hasil', p_hasil
    );
END;
$$;

-- ============================================
-- 7. FUNCTION UNTUK STATISTIK ADMIN
-- ============================================
CREATE OR REPLACE FUNCTION get_statistik_wawancara()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    stats JSONB;
BEGIN
    SELECT jsonb_build_object(
        'total_peserta', (SELECT COUNT(*) FROM public.peserta),
        'terdaftar', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Terdaftar'),
        'menunggu', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Menunggu'),
        'diwawancara', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Diwawancara'),
        'lulus', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Lulus'),
        'tidak_lulus', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Tidak Lulus'),
        'ditinjau', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Ditinjau'),
        'tidak_hadir', (SELECT COUNT(*) FROM public.peserta WHERE status = 'Tidak Hadir'),
        'rata_nilai', (SELECT COALESCE(ROUND(AVG(nilai_total)::numeric, 1), 0) FROM public.peserta WHERE nilai_total > 0),
        'rata_durasi_menit', (SELECT COALESCE(ROUND(AVG(durasi_wawancara) / 60.0, 1), 0) FROM public.peserta WHERE durasi_wawancara > 0)
    ) INTO stats;
    
    RETURN stats;
END;
$$;

-- ============================================
-- 8. VIEW UNTUK ANTREAN REALTIME
-- ============================================
CREATE OR REPLACE VIEW public.antrean_hari_ini AS
SELECT 
    id,
    nik,
    sobat_id,
    nama,
    pasfoto_url,
    nomor_antrean,
    status,
    pendidikan_terakhir,
    pekerjaan,
    updated_at
FROM public.peserta
WHERE status IN ('Menunggu', 'Diwawancara')
ORDER BY 
    CASE WHEN status = 'Diwawancara' THEN 0 ELSE 1 END,
    nomor_antrean ASC;

-- ============================================
-- 9. ENABLE REALTIME UNTUK PESERTA
-- ============================================
-- Pastikan realtime subscription aktif
ALTER PUBLICATION supabase_realtime ADD TABLE public.peserta;

-- ============================================
-- SAMPLE DATA (Opsional - untuk testing)
-- ============================================
-- INSERT INTO public.peserta (nik, sobat_id, nama, alamat_lengkap, pendidikan_terakhir, pekerjaan) VALUES
-- ('3301017670101001', '331023110301', 'Pingki Setriana', 'Jl. Merdeka No. 45, Malang', 'S1', 'Wiraswasta'),
-- ('3310105510920001', '331022020080', 'Heni Purnama Sari', 'Jl. Sudirman No. 12, Surabaya', 'D3', 'Mahasiswa'),
-- ('3310011412950001', '331022020069', 'Daiyan Agung Santosa', 'Jl. Diponegoro No. 78, Bandung', 'SMA', 'Freelancer');

-- ============================================
-- SELESAI!
-- ============================================
-- Schema database siap untuk:
-- 1. Upload data peserta dari Sobat BPS (Excel/CSV)
-- 2. Check-in peserta dengan verifikasi NIK
-- 3. Sistem antrean wawancara real-time
-- 4. Penilaian dan rekap hasil
-- ============================================
