-- ============================================
-- INTERVIEW QUEUE SYSTEM - SUPABASE SETUP
-- ============================================
-- Jalankan script ini di SQL Editor Supabase
-- Dashboard > SQL Editor > New Query
-- ============================================

-- 1. Buat Tipe Data Enum untuk standarisasi status
CREATE TYPE user_role AS ENUM ('admin', 'interviewer', 'candidate');
CREATE TYPE queue_status AS ENUM ('registered', 'waiting', 'assigned', 'interviewing', 'completed', 'skipped');
CREATE TYPE interviewer_state AS ENUM ('offline', 'idle', 'busy', 'break');

-- 2. Tabel Profiles (Sinkronisasi data user dari Clerk)
-- Note: id di sini adalah TEXT karena Clerk ID berupa string (misal: user_2xBg...)
CREATE TABLE public.profiles (
    id TEXT PRIMARY KEY, 
    email TEXT,
    full_name TEXT,
    role user_role DEFAULT 'candidate',
    interviewer_status interviewer_state DEFAULT 'offline',
    specialization TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabel Jobs (Lowongan)
CREATE TABLE public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabel Applications (Antrean Utama)
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT REFERENCES public.profiles(id) NOT NULL,
    job_id BIGINT REFERENCES public.jobs(id) NOT NULL,
    queue_number VARCHAR(10),
    status queue_status DEFAULT 'registered',
    cv_url TEXT,
    checked_in_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabel Sessions (Sesi Wawancara Aktif/Historis)
CREATE TABLE public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT REFERENCES public.applications(id),
    interviewer_id TEXT REFERENCES public.profiles(id),
    room_link TEXT,
    score_summary JSONB,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE
);

-- 6. Indexing untuk mempercepat pencarian antrean
CREATE INDEX idx_queue_lookup ON public.applications(status, checked_in_at);
CREATE INDEX idx_interviewer_lookup ON public.profiles(interviewer_status);
CREATE INDEX idx_applications_candidate ON public.applications(candidate_id);
CREATE INDEX idx_sessions_interviewer ON public.sessions(interviewer_id);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS pada semua tabel
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Policy untuk Profiles
CREATE POLICY "Users can view own profile" 
ON public.profiles FOR SELECT 
USING (true);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid()::text = id);

CREATE POLICY "Service role can insert profiles" 
ON public.profiles FOR INSERT 
WITH CHECK (true);

-- Policy untuk Jobs (semua bisa lihat)
CREATE POLICY "Everyone can view active jobs" 
ON public.jobs FOR SELECT 
USING (is_active = true);

CREATE POLICY "Admins can manage jobs" 
ON public.jobs FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role = 'admin'
  )
);

-- Policy untuk Applications
CREATE POLICY "Candidates can view own applications" 
ON public.applications FOR SELECT 
USING (candidate_id = auth.uid()::text);

CREATE POLICY "Candidates can insert own applications" 
ON public.applications FOR INSERT 
WITH CHECK (candidate_id = auth.uid()::text);

CREATE POLICY "Candidates can update own applications" 
ON public.applications FOR UPDATE 
USING (candidate_id = auth.uid()::text);

CREATE POLICY "Interviewers can view all applications" 
ON public.applications FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role IN ('admin', 'interviewer')
  )
);

CREATE POLICY "Interviewers can update applications" 
ON public.applications FOR UPDATE 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role IN ('admin', 'interviewer')
  )
);

-- Policy untuk Sessions
CREATE POLICY "Interviewers can view own sessions" 
ON public.sessions FOR SELECT 
USING (
  interviewer_id = auth.uid()::text OR
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role = 'admin'
  )
);

CREATE POLICY "Interviewers can insert sessions" 
ON public.sessions FOR INSERT 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid()::text AND role IN ('admin', 'interviewer')
  )
);

CREATE POLICY "Interviewers can update own sessions" 
ON public.sessions FOR UPDATE 
USING (interviewer_id = auth.uid()::text);

-- ============================================
-- STORED PROCEDURE: AUTO-ASSIGN KANDIDAT
-- ============================================

CREATE OR REPLACE FUNCTION request_next_candidate(interviewer_id_input TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    matched_application_id BIGINT;
    candidate_info JSONB;
BEGIN
    -- 1. Pastikan status interviewer jadi IDLE dulu
    UPDATE public.profiles 
    SET interviewer_status = 'idle' 
    WHERE id = interviewer_id_input;

    -- 2. CARI KANDIDAT: Ambil 1 kandidat terlama yang statusnya 'waiting'
    SELECT id INTO matched_application_id
    FROM public.applications
    WHERE status = 'waiting'
    ORDER BY checked_in_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED;

    -- 3. JIKA KANDIDAT DITEMUKAN
    IF matched_application_id IS NOT NULL THEN
        
        -- A. Update Status Interviewer jadi BUSY
        UPDATE public.profiles 
        SET interviewer_status = 'busy' 
        WHERE id = interviewer_id_input;

        -- B. Update Status Aplikasi jadi ASSIGNED
        UPDATE public.applications 
        SET status = 'assigned' 
        WHERE id = matched_application_id;

        -- C. Buat Sesi Baru
        INSERT INTO public.sessions (application_id, interviewer_id, started_at)
        VALUES (matched_application_id, interviewer_id_input, NOW());

        -- D. Kembalikan data kandidat ke Interviewer
        SELECT jsonb_build_object(
            'status', 'success',
            'application_id', matched_application_id
        ) INTO candidate_info;
        
        RETURN candidate_info;

    ELSE
        -- Jika tidak ada antrean
        RETURN jsonb_build_object(
            'status', 'empty', 
            'message', 'Tidak ada antrean saat ini.'
        );
    END IF;
END;
$$;

-- ============================================
-- ENABLE REALTIME
-- ============================================

-- Enable realtime untuk tabel yang perlu realtime updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.applications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sessions;

-- ============================================
-- SAMPLE DATA (Opsional - untuk testing)
-- ============================================

-- Insert sample jobs
INSERT INTO public.jobs (title, is_active) VALUES 
('Frontend Developer', true),
('Backend Developer', true),
('UI/UX Designer', true),
('Data Analyst', true),
('DevOps Engineer', true);

-- ============================================
-- SELESAI!
-- ============================================
-- Langkah selanjutnya:
-- 1. Setup Clerk dan dapatkan API keys
-- 2. Setup Webhook di Clerk untuk sync user
-- 3. Copy environment variables ke .env.local
-- 4. Deploy ke Vercel
-- ============================================
